FROM python:3.8-alpine
LABEL maintainer="paganism@mail.ru"
WORKDIR /usr/app/site_learn_it/
RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev
EXPOSE 8000
COPY ./site_learn_it ./.env ./requirements.txt ./
RUN pip install -r requirements.txt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]