# Generated by Django 3.0.2 on 2020-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_it', '0002_course_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timetable',
            field=models.TextField(blank=True, choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=256, null=True, verbose_name='день недели'),
        ),
    ]
