# Generated by Django 3.0.2 on 2020-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_it', '0004_auto_20200130_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.ManyToManyField(to='learn_it.Days'),
        ),
    ]
