# Generated by Django 3.0.2 on 2020-01-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_it', '0008_auto_20200130_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.ManyToManyField(related_name='days', to='learn_it.Days'),
        ),
    ]
