# Generated by Django 3.0.2 on 2020-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_it', '0009_auto_20200130_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.ManyToManyField(related_name='courses', to='learn_it.Days'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
